price-of-sugarcane: 10.0
name-of-harvesterhoe-currency: 'Essence'

item-name: '&5&l*** &d&lHarvester Hoe &5&l***'

item-lore:
  - '&6Don''t Have To Pickup Sugarcane Anymore!'
  - ''
  - '&7&lHaste: &6{hasteValue}'
  - '&7&lRadius: &6{radiusValue}'
  - '&7&lAutosell: &6{autosellValue} &8({autosellEnabled})'
  - '&7&lSell Multiplier: &6{sellMultiplierValue}'

upgrade-item-name: '&5&l*** &6&l{type} Upgrade &5&l***'

upgrade-item-lore:
  - ''
  - '&7&lCurrent Value: &6{currentValue}'
  - '&7&lNext Value: &6{nextValue}'
  - '&7&lPrice: &6{price}'

currency-item-name: '&a&lAmount of {currency}'
currency-item-lore:
  - ''
  - '&7You currently have: &6{currentValue} &7{currency}.'

max-haste: 5
max-radius: 3
max-sell-multiplier: 2.0

# Formula for exponent rates (rate is r, starting value is a, x is level):
# f(x) = a(1+r)^x

haste-price-start: 100.0
haste-price-exponent-rate: 1.15

radius-price-start: 1000.0
radius-price-exponent-rate: 1.5

sell-multiplier-price-start: 1000.0
sell-multiplier-price-exponent-rate: 1.15

autosell-price: 100000.0

sell-multiplper-increment: 0.05

item-sent-message: '&a&l(!) &aTarget received a HarvesterHoe!'

item-recieved-message: '&a&l(!) &aYou have received a HarvesterHoe!'

balance-message: '&a&l(!) &aYou currently have {amount} {customCurrency}.'

change-balance-message: '&a&l(!) &a{player}''s balance has been successfully set to {amount} {customCurrency}.'

changed-balance-message: '&a&l(!) &aYour balance has been set to {amount} {customCurrency}.'

money-in-last-minute-message: '&a&l(!) &aYou have earned ${amount} in the last minute from selling sugarcane.'

no-permission-message: '&c&l(!) &cYou do not have the permission to execute this command!'

no-hoe-message: '&c&l(!) &cPlease hold a harvester hoe in your hand before running this command!'

stat-already-maxed-message: '&c&l(!) &c{type} is already at the maximum value!'

too-poor-message: '&c&l(!) &cYou cannot afford this upgrade!'

successful-upgrade-purchase-message: '&c&l(!) &aYou have successfully upgraded your harvester hoe''s {type} for {price}!'

toggle-autosell-message: '&c&l(!) &aYou have {value} AutoSell!'

recently-placed-message: '&c&l(!) &cYou can''t break that block since you just placed it!'